import {
  Box,
  Text,
  Heading,
  HStack,
  VStack,
  Spacer,
  SimpleGrid,
  Stack,
  Skeleton,
  Image,
  Span,
} from "@chakra-ui/react";

import type { StudentProfileType } from "../../types/StudentTypes";
import { BsStars } from "react-icons/bs";
import ProfileImageSection from "./ProfileImageSection";

import visionIcon from "../../assets/map.png";
import skillIcon from "../,,/../../assets/icons/like.png";
import longTermGoalIcon from "../../assets/icons/businessman.png";
import bestWayIcon from "../../assets/icons/handshake.png";

interface StudentPageCardProps {
  student: StudentProfileType | null;
  profileLoading: boolean;
  triggerRefetch: () => void;
}

const StudentPageCard = ({
  student,
  profileLoading,
  triggerRefetch,
}: StudentPageCardProps) => {
  return (
    <Stack
      w="100%"
      direction={{ base: "column", md: "row" }}
      spaceY={{ base: 4, md: 0 }}
      align="stretch"
      color="white"
      borderRadius="lg"
    >
      {/* Profile Image */}
      <ProfileImageSection
        studentId={student?.student_id}
        profilePictureUrl={student?.profile_picture_url}
        imageLoading={profileLoading}
        triggerRefetch={triggerRefetch}
      />

      {/* Right Content */}

      {profileLoading ? (
        <Skeleton spaceY={2} flex={1} bg="#244D8A" borderRadius="lg" p={6} />
      ) : (
        <VStack align="start" flex={1} bg="#244D8A" borderRadius="lg" p={6}>
          {/* Name and Year */}
          <HStack w="100%">
            <Heading size="2xl">
              {student?.first_name} {student?.last_name}
            </Heading>
            <Spacer />
            <HStack
              bg="#BD4F23"
              color="white"
              px={3}
              py={1}
              borderRadius="full"
              shadow="xl"
            >
              <BsStars color="white" />
              Generated by AI
            </HStack>
          </HStack>

          {/* <HStack spaceX={4} mt={2}>
            <Box bg="#BD4F23" color="white" px={3} py={1} borderRadius="xl">
              Year: <b>{student?.year_name}</b>
            </Box>
            <Box bg="#BD4F23" color="white" px={3} py={1} borderRadius="xl">
              Classes:{" "}
              <Text as="span" fontWeight="bold">
                {student?.classes.map((c) => c.class_name).join(", ")}
              </Text>
            </Box>
          </HStack> */}

          {/* Vision Statement (Full width) */}
          <Box w="100%">

            <Text bg={"white"} p={2} borderRadius={"lg"} color={"black"}>
              {" "}
              <Span fontWeight="bold" pr={3}>Vision Statement:</Span>
              {student?.profile_summaries.vision}
            </Text>
          </Box>

          {/* Grid for 4 remaining sections */}
          <SimpleGrid columns={{ base: 1, md: 2 }} gap={6} w="100%">
            <Box>
              <HStack mb={1} align={"center"}>
                <Image src={skillIcon} height="40px" />
                <Text fontWeight="bold" >Skill Summary</Text>
              </HStack>
              <Text bg={"white"} color={"black"} p={3} borderRadius={"lg"}>
                {student?.profile_summaries.strengths_short}
              </Text>
            </Box>

            <Box>
              <HStack mb={1} align={"center"}>
                <Image src={bestWayIcon} height="40px" />

                <Text  fontWeight="bold">Best Way to assist me is:</Text>
              </HStack>
              <Text bg={"white"} color={"black"} p={3} borderRadius={"lg"}>
                {student?.profile_summaries.best_ways_to_help}
              </Text>
            </Box>

            <Box>
              <HStack mb={1} align={"center"}>
                <Image src={longTermGoalIcon} height="40px" />
                <Text fontWeight="bold">After college I want to:</Text>
              </HStack>
              <Text bg={"white"} color={"black"} p={3} borderRadius={"lg"}>
                {student?.profile_summaries.long_term_goals}
              </Text>
            </Box>

            <Box>
              <HStack mb={1} align={"center"}>
                <Image src={visionIcon} height="40px" />
                <Text fontWeight="bold">Currently I want to achieve:</Text>
              </HStack>
              <Text bg={"white"} color={"black"} p={3} borderRadius={"lg"}>
                {student?.profile_summaries.short_term_goals}
              </Text>
            </Box>
          </SimpleGrid>
        </VStack>
      )}
    </Stack>
  );
};

export default StudentPageCard;
